/**
 * This file is autogenerated by scaffold-stylus.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "../utils/scaffold-eth/contract";

const deployedContracts = {
  "421614": {
    "your-contract": {
      address: "0x08961372117ba89cac48ea7396521f8ee7bc2137",
      txHash: "0xf4558869299157450c6a4408d05711df12c68cc03c8b6d2085d2fa7c32fbbbf1",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "contract_address",
              type: "address",
            },
          ],
          name: "callView",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
